---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Notes
### Attention-restoration theory (ART)  
#### Definition  
Nature invokes involuntary attention modestly, allowing directed-attention mechanisms a chance to replenish (Kaplan, 1995).  

We are subjected up to 11 million bits of info per second in cites and can process only 15-20 total

#### Tools  
directed-attention mechanisms are restored by simple natural experiences
walk, observation of natural systems, controls were walks or sitting in urban versus more natural systems  
memory tests like backward span test
changing task tests to examine executive functions  
rumination, anxiety  

#### Implications  
Creative performance dramatically enhanced  
Creativity requires diffuse attention and incubation  
Stimulates curiosity and flexibility

### Biophilia (BET)  

#### Definition  
evolutionary history & connectedness generate an innate design to connect with nature Kellert & E.O. Wilson 1993 rationale -evolutionary drive to search for survival enhancing settings
utilitarian, naturalistic, ecoloogical, aesthetic, symbolic, humanistic, moralistic etc  

#### Tools  
scientific inquiry of nature, engaging with the senses, creating natural places, conservation, growing food, connecting with the wild   
visual contact with nature  
emotional support dogs  
urban gardens  
the lovebug effect with microbial biomediation - driver-passenger and health on autonomic nervous systems  

#### Implications  
reduce stress, improve cognitive function, and enhance mood and creativity  
performance - evidence that support physiological recovery, collectively terms healing   

### Stress-reduction therapy (SRT)  
#### Definition  
Stress reduction theory (SRT) provides an explanation for the impact of nature experience on affect. This theory posits that natural environments have a restorative advantage over artificial environments due to the role that they played in our evolution as a species (Ulrich, 1979)

#### Tools  
viewing visual landscapes  
higher levels of natural complexity ie in forests such as through vegetation can elicit greater benefits

#### Implications  
fear, anxiety, resting HR, respiration, anger and aggressions, sadness, attentivemness improve  
moderates activation cognitively, ie attenuates cognitive arousal  
facilitation emotional support for defocussed creative performance in the ideation phase  


### Environmental identity — labeling  

### Definition  
urban nature including trees, water, and simple open spaces can provide an 'escape' and alternative self-applied labels particularly in children  
liminal places in cities provide an opportinity to try on new labels, ie ecofriendly

#### Tools  
time, space, lack of structure  

#### Implications  
addressing nature deficit disorder and can directly influence mental health and general well-being  

### Visual complexity

### Definition  
Work from the SRT hypothesis suggest that relative more complex patterns generate higher benefits
however evidence suggest tipping points in the complexity needed  

### Tools
Imagery, green walls, even manicured nature
how low can you go - outside better than inside might be sufficient for performance enhancements   

### Risky play
#### Definition  
Less structure, more permeable places and surfaces, and less rules generate higher cognitive returns

#### Tools  
More adventure, less lines  

#### Implications  
Open places with less rules and less pre-determined function can provide novel and stimulating playgrounds at least for children - but perhaps adults too!  
